

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v1.0.1
        with:
          nekoweb-api-key: ${{ secrets.NEKO_WEB_API_KEY }}
          nekoweb-domain: 'foryoureyesonly.nekoweb.org'
          nekoweb-username: 'foryoureyesonly'
          directory: '../../generated'

